[theme]
base = 'dark'
primaryColor = '#ffa200'
backgroundColor = '#0a0a0a'
secondaryBackgroundColor = '#101010'
textColor = '#fafafa'
linkColor = '#ffa200'
codeBackgroundColor = '#101010'
font = 'Plus Jakarta Sans'
baseFontSize = 16
baseFontWeight = 500
headingFont = 'Plus Jakarta Sans'
headingFontSizes = ['2.75rem', '2.25rem', '1.75rem', '1.5rem', '1.25rem', '1rem']
headingFontWeights = 600
codeFont = 'monospace'
codeFontSize = '1rem'
codeFontWeight = 400
baseRadius = 'medium'
buttonRadius = 'medium'
borderColor = '#1f1f1f'
dataframeBorderColor = '#1f1f1f'
dataframeHeaderBackgroundColor = '#101010'